// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Customizable screener to retrieve reference data : this is a prototype, to be completed
syntax = "proto3";

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";

import "systemathics/apis/services/calendar/v1/calendar.proto";

package systemathics.apis.services.calendar.v1;

// Called to request screener data.
service TradingHoursService
{
	// Gets currencies with holidays information 
	rpc SetTradingHours(SetTradingHoursRequest) returns (google.protobuf.Empty)
	{
	 	option (google.api.http) = {
			post: "/v1/calendar/trading_hours"
		};
	}
}

message SetTradingHoursRequest
{
	repeated systemathics.apis.services.calendar.v1.TradingHoursMessage trading_hours = 1;
}
