// Copyright (c) 2021 Systemathics
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Intraday prices illustrates intraday price movements for an instrument over a look back period.
syntax = "proto3";


import "google/protobuf/empty.proto";
import "google/api/annotations.proto";
import "google/type/datetime.proto";
import "google/protobuf/struct.proto";

import "systemathics/apis/type/shared/v1/asset.proto";
import "systemathics/apis/type/shared/v1/identifier.proto";
import "systemathics/apis/type/shared/v1/date_interval.proto";
import "systemathics/apis/type/shared/v1/sampling.proto";
import "systemathics/apis/type/shared/v2/set_data_mode.proto";

package systemathics.apis.services.intraday.v2;

// Called to set intraday prices data and clear. 
service SetIntradayService
{
  // Sets intraday scalar timeseries.
  rpc WriteIntradayScalar(SetIntradayScalarRequest) returns (google.protobuf.Empty)
  {
	  option (google.api.http) = {
			post: "/v2/intraday_scalar"
	  };
  }
  
  rpc WriteIntradayScalarStream(stream SetIntradayScalarStreamRequest) returns (google.protobuf.Empty)
  {
	  option (google.api.http) = {
			post: "/v2/intraday_scalar"
	  };
  }

  // Sets intraday vector timeseries.
  rpc WriteIntradayVector(SetIntradayVectorRequest) returns (google.protobuf.Empty)
  {
	  option (google.api.http) = {
			post: "/v2/intraday_vector"
	  };
  }

  // Sets intraday vector timeseries.
  rpc WriteIntradayVectorStream(stream SetIntradayVectorStreamRequest) returns (google.protobuf.Empty)
  {
	  option (google.api.http) = {
			post: "/v2/intraday_vector"
	  };
  }

  // Update intraday scalar timeseries.
  rpc UpdateIntradayScalar(SetIntradayScalarRequest) returns (google.protobuf.Empty)
  {
	  option (google.api.http) = {
			put: "/v2/intraday_scalar"
	  };
  }

  // Update intraday scalar timeseries.
  rpc UpdateIntradayScalarStream(stream SetIntradayScalarStreamRequest) returns (google.protobuf.Empty)
  {
	  option (google.api.http) = {
			put: "/v2/intraday_scalar"
	  };
  }

  
  // Update intraday vectors timeseries.
  rpc UpdateIntradayVector(SetIntradayVectorRequest) returns (google.protobuf.Empty)
  {
	  option (google.api.http) = {
			put: "/v2/intraday_vector"
	  };
  }

    // Update intraday vectors timeseries.
  rpc UpdateIntradayVectorStream(stream SetIntradayVectorStreamRequest) returns (google.protobuf.Empty)
  {
	  option (google.api.http) = {
			put: "/v2/intraday_vector"
	  };
  }

  // Delete intraday scalar timeseries.
  rpc DeleteIntradayScalar(DeleteIntradayScalarRequest) returns (google.protobuf.Empty)
  {
	  option (google.api.http) = {
			delete: "/v2/intraday_scalar"
	  };
  }

    // Delete intraday scalar timeseries.
  rpc DeleteIntradayVector(DeleteIntradayVectorRequest) returns (google.protobuf.Empty)
  {
	  option (google.api.http) = {
			delete: "/v2/intraday_vector"
	  };
  }
}

// The required input to request the SetDailyScalar endpoint
message SetIntradayScalarRequest
{
	// [Mandatory] The instrument identifiers: a bloomberg dailyer and an asset type
	systemathics.apis.type.shared.v1.Identifier identifier = 1;

	// [Mandatory] The sampling interval
	systemathics.apis.type.shared.v1.Sampling sampling = 2;

	// [Mandatory] The date used to request data.
	google.type.DateTime datetime = 3;	

	// [Mandatory] The data with field as a key
	map<string, double> data = 4;
}



// The required input to request the SetIntradayScalar endpoint
message SetIntradayScalarStreamRequest
{
	oneof payload 
	{
		// The intraday info
		SetIntradayInfo info = 1;
		
		// The mapping data
		SetIntradayScalarData data = 2;
	}
}


// The required input to request the SetIntradayScalar endpoint
message SetIntradayVectorRequest
{
	// [Mandatory] The instrument identifiers: a bloomberg ticker and an asset type
	systemathics.apis.type.shared.v1.Identifier identifier = 1;

	// [Mandatory] The sampling interval
	systemathics.apis.type.shared.v1.Sampling sampling = 2;

	// [Mandatory] The date used to request data.
	google.type.DateTime datetime = 3;	

	// [Mandatory] The vector key.
	string key = 4;

	// [Mandatory] The data with field as a key
	map<string, double> data = 5;
}

// The required input to request the SetIntradayScalar endpoint
message SetIntradayVectorStreamRequest
{
	oneof payload 
	{
		// The tick info
		SetIntradayInfo info = 1;
		
		// The mapping data
		SetIntradayVectorData data = 2;
	}
}

// The required input to request DeleteIntradayScalar.
message DeleteIntradayScalarRequest 
{
	// [Mandatory] The instrument identifiers: a bloomberg ticker and an asset type
	systemathics.apis.type.shared.v1.Identifier identifier = 1;

	// [Mandatory] The sampling interval
	systemathics.apis.type.shared.v1.Sampling sampling = 2;

	// [Mandatory] The fields to be deleted.
	repeated string fields = 3;

	// [Mandatory] The dates to be deleted.
	repeated google.type.DateTime dates = 4;
}


// The required input to request DeleteIntradayScalar.
message DeleteIntradayVectorRequest 
{
	// [Mandatory] The instrument identifiers: a bloomberg ticker and an asset type
	systemathics.apis.type.shared.v1.Identifier identifier = 1;

	// [Mandatory] The sampling interval
	systemathics.apis.type.shared.v1.Sampling sampling = 2;

	// [Mandatory] The fields to be deleted.
	repeated string fields = 3;

	// [Mandatory] The keys to be deleted.
	repeated VectorKey keys = 4;
}


// The required input to request the GetIntradayByDate endpoint
message SetIntradayInfo
{
	// [Mandatory] The instrument identifiers: a bloomberg ticker and an asset type
	systemathics.apis.type.shared.v1.Identifier identifier = 1;

	// [Mandatory] The sampling interval
	systemathics.apis.type.shared.v1.Sampling sampling = 2;

	// [Mandatory] The data names.
	repeated string fields = 3;
}

// Represent the data to be added to the data scalar timeseries.
message SetIntradayScalarData
{
	// [Mandatory] The date used to request data.
	google.type.DateTime datetime = 1;

	// [Mandatory] The date used to request data.
	repeated double data = 2;
}

// Represent the key for a vector.
message VectorKey {
	// [Mandatory] The date used to request data.
	google.type.DateTime datetime = 1;

	// [Mandatory] The vector key.
	string key = 2;
}
 

// Represent the data to be added to the data vector timeseries.
message SetIntradayVectorData
{
	// [Mandatory] The date used to request data.
	google.type.DateTime datetime = 1;

	// [Mandatory] The vector key.
	string key = 2;

	// [Mandatory] The data.
	repeated double data = 3;
}
 
